/**
 * Copyright (c) HashiCorp, Inc.
 * SPDX-License-Identifier: MPL-2.0
 */

// generated by cdktf get
Object.defineProperty(exports, 'accessPackage', { get: function () { return require('./access-package'); } });
Object.defineProperty(exports, 'accessPackageAssignmentPolicy', { get: function () { return require('./access-package-assignment-policy'); } });
Object.defineProperty(exports, 'accessPackageCatalog', { get: function () { return require('./access-package-catalog'); } });
Object.defineProperty(exports, 'accessPackageCatalogRoleAssignment', { get: function () { return require('./access-package-catalog-role-assignment'); } });
Object.defineProperty(exports, 'accessPackageResourceCatalogAssociation', { get: function () { return require('./access-package-resource-catalog-association'); } });
Object.defineProperty(exports, 'accessPackageResourcePackageAssociation', { get: function () { return require('./access-package-resource-package-association'); } });
Object.defineProperty(exports, 'administrativeUnit', { get: function () { return require('./administrative-unit'); } });
Object.defineProperty(exports, 'administrativeUnitMember', { get: function () { return require('./administrative-unit-member'); } });
Object.defineProperty(exports, 'administrativeUnitRoleMember', { get: function () { return require('./administrative-unit-role-member'); } });
Object.defineProperty(exports, 'appRoleAssignment', { get: function () { return require('./app-role-assignment'); } });
Object.defineProperty(exports, 'application', { get: function () { return require('./application'); } });
Object.defineProperty(exports, 'applicationCertificate', { get: function () { return require('./application-certificate'); } });
Object.defineProperty(exports, 'applicationFederatedIdentityCredential', { get: function () { return require('./application-federated-identity-credential'); } });
Object.defineProperty(exports, 'applicationPassword', { get: function () { return require('./application-password'); } });
Object.defineProperty(exports, 'applicationPreAuthorized', { get: function () { return require('./application-pre-authorized'); } });
Object.defineProperty(exports, 'claimsMappingPolicy', { get: function () { return require('./claims-mapping-policy'); } });
Object.defineProperty(exports, 'conditionalAccessPolicy', { get: function () { return require('./conditional-access-policy'); } });
Object.defineProperty(exports, 'customDirectoryRole', { get: function () { return require('./custom-directory-role'); } });
Object.defineProperty(exports, 'directoryRole', { get: function () { return require('./directory-role'); } });
Object.defineProperty(exports, 'directoryRoleAssignment', { get: function () { return require('./directory-role-assignment'); } });
Object.defineProperty(exports, 'directoryRoleMember', { get: function () { return require('./directory-role-member'); } });
Object.defineProperty(exports, 'group', { get: function () { return require('./group'); } });
Object.defineProperty(exports, 'groupMember', { get: function () { return require('./group-member'); } });
Object.defineProperty(exports, 'invitation', { get: function () { return require('./invitation'); } });
Object.defineProperty(exports, 'namedLocation', { get: function () { return require('./named-location'); } });
Object.defineProperty(exports, 'servicePrincipal', { get: function () { return require('./service-principal'); } });
Object.defineProperty(exports, 'servicePrincipalCertificate', { get: function () { return require('./service-principal-certificate'); } });
Object.defineProperty(exports, 'servicePrincipalClaimsMappingPolicyAssignment', { get: function () { return require('./service-principal-claims-mapping-policy-assignment'); } });
Object.defineProperty(exports, 'servicePrincipalDelegatedPermissionGrant', { get: function () { return require('./service-principal-delegated-permission-grant'); } });
Object.defineProperty(exports, 'servicePrincipalPassword', { get: function () { return require('./service-principal-password'); } });
Object.defineProperty(exports, 'servicePrincipalTokenSigningCertificate', { get: function () { return require('./service-principal-token-signing-certificate'); } });
Object.defineProperty(exports, 'synchronizationJob', { get: function () { return require('./synchronization-job'); } });
Object.defineProperty(exports, 'synchronizationSecret', { get: function () { return require('./synchronization-secret'); } });
Object.defineProperty(exports, 'user', { get: function () { return require('./user'); } });
Object.defineProperty(exports, 'userFlowAttribute', { get: function () { return require('./user-flow-attribute'); } });
Object.defineProperty(exports, 'dataAzureadAccessPackage', { get: function () { return require('./data-azuread-access-package'); } });
Object.defineProperty(exports, 'dataAzureadAccessPackageCatalog', { get: function () { return require('./data-azuread-access-package-catalog'); } });
Object.defineProperty(exports, 'dataAzureadAccessPackageCatalogRole', { get: function () { return require('./data-azuread-access-package-catalog-role'); } });
Object.defineProperty(exports, 'dataAzureadAdministrativeUnit', { get: function () { return require('./data-azuread-administrative-unit'); } });
Object.defineProperty(exports, 'dataAzureadApplication', { get: function () { return require('./data-azuread-application'); } });
Object.defineProperty(exports, 'dataAzureadApplicationPublishedAppIds', { get: function () { return require('./data-azuread-application-published-app-ids'); } });
Object.defineProperty(exports, 'dataAzureadApplicationTemplate', { get: function () { return require('./data-azuread-application-template'); } });
Object.defineProperty(exports, 'dataAzureadClientConfig', { get: function () { return require('./data-azuread-client-config'); } });
Object.defineProperty(exports, 'dataAzureadDirectoryObject', { get: function () { return require('./data-azuread-directory-object'); } });
Object.defineProperty(exports, 'dataAzureadDirectoryRoleTemplates', { get: function () { return require('./data-azuread-directory-role-templates'); } });
Object.defineProperty(exports, 'dataAzureadDirectoryRoles', { get: function () { return require('./data-azuread-directory-roles'); } });
Object.defineProperty(exports, 'dataAzureadDomains', { get: function () { return require('./data-azuread-domains'); } });
Object.defineProperty(exports, 'dataAzureadGroup', { get: function () { return require('./data-azuread-group'); } });
Object.defineProperty(exports, 'dataAzureadGroups', { get: function () { return require('./data-azuread-groups'); } });
Object.defineProperty(exports, 'dataAzureadNamedLocation', { get: function () { return require('./data-azuread-named-location'); } });
Object.defineProperty(exports, 'dataAzureadServicePrincipal', { get: function () { return require('./data-azuread-service-principal'); } });
Object.defineProperty(exports, 'dataAzureadServicePrincipals', { get: function () { return require('./data-azuread-service-principals'); } });
Object.defineProperty(exports, 'dataAzureadUser', { get: function () { return require('./data-azuread-user'); } });
Object.defineProperty(exports, 'dataAzureadUsers', { get: function () { return require('./data-azuread-users'); } });
Object.defineProperty(exports, 'provider', { get: function () { return require('./provider'); } });

